import { PrismaClient } from '../src/generated/prisma/client';
import { PrismaBetterSqlite3 } from '@prisma/adapter-better-sqlite3';

import * as path from 'path';

const dbPath = path.resolve(__dirname, 'dev.db');
const adapter = new PrismaBetterSqlite3({
  url: `file:${dbPath}`,
});
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('🌱 Starting database seed...');

  // ─── Clear all tables ──────────────────────────────────────
  console.log('Clearing existing data...');
  await prisma.activityLog.deleteMany();
  await prisma.scheduledContent.deleteMany();
  await prisma.setting.deleteMany();
  await prisma.promoCode.deleteMany();
  await prisma.wishlistItem.deleteMany();
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.subscriber.deleteMany();
  await prisma.inquiry.deleteMany();
  await prisma.testimonial.deleteMany();
  await prisma.pressItem.deleteMany();
  await prisma.journalPost.deleteMany();
  await prisma.campaign.deleteMany();
  await prisma.workshop.deleteMany();
  await prisma.productVariant.deleteMany();
  await prisma.product.deleteMany();
  await prisma.artwork.deleteMany();
  await prisma.collection.deleteMany();
  await prisma.user.deleteMany();
  console.log('All tables cleared.');

  // ─── Users ─────────────────────────────────────────────────
  console.log('Seeding users...');
  const adminUser = await prisma.user.create({
    data: {
      id: 'user-admin-1',
      email: 'demo@monaniko.com',
      password: 'demo',
      firstName: 'Mona',
      lastName: 'Niko',
      role: 'ADMIN',
    },
  });
  console.log(`  Created admin user: ${adminUser.email}`);

  // ─── Collections ───────────────────────────────────────────
  console.log('Seeding collections...');
  const collectionsData = [
    {
      id: 'col-1',
      title: 'Portraits of Strength',
      slug: 'portraits-of-strength',
      description: 'A powerful series celebrating the resilience, beauty, and complexity of women. Each work in this collection captures a different facet of feminine strength — from quiet determination to bold defiance.',
      coverImage: '/images/artworks/artwork-1.jpg',
      featured: true,
      year: 2024,
    },
    {
      id: 'col-2',
      title: 'Persian Heritage',
      slug: 'persian-heritage',
      description: 'Drawing deeply from the rich artistic traditions of Iran, this collection bridges centuries of cultural expression. Qajar-era portraiture, Eslimi arabesque patterns, and Persian symbolism are reinterpreted through a contemporary lens.',
      coverImage: '/images/artworks/artwork-5.jpg',
      featured: true,
      year: 2023,
    },
    {
      id: 'col-3',
      title: 'Abstract Emotions',
      slug: 'abstract-emotions',
      description: 'An intimate journey through the landscape of human feeling. These works move beyond representation to capture the essence of love, hope, longing, and inner peace.',
      coverImage: '/images/artworks/artwork-3.jpg',
      featured: true,
      year: 2024,
    },
    {
      id: 'col-4',
      title: 'Luminous',
      slug: 'luminous',
      description: 'A collection exploring light, radiance, and the luminous qualities of color. Each piece captures the way light transforms perception, creating works that seem to glow from within.',
      coverImage: '/images/artworks/artwork-2.jpg',
      featured: false,
      year: 2025,
    },
    {
      id: 'col-5',
      title: 'Modern Portraits',
      slug: 'modern-portraits',
      description: 'Contemporary portraits that capture the spirit of modern life. Bold, expressive, and deeply personal, these works redefine portraiture for a new generation.',
      coverImage: '/images/artworks/artwork-7.jpg',
      featured: false,
      year: 2025,
    },
  ];

  for (const col of collectionsData) {
    await prisma.collection.create({ data: col });
  }
  console.log(`  Created ${collectionsData.length} collections.`);

  // ─── Artworks ──────────────────────────────────────────────
  console.log('Seeding artworks...');
  const artworksData = [
    {
      id: 'art-1',
      title: 'Layers of the Soul',
      slug: 'layers-of-the-soul',
      description: 'A deeply introspective mixed media painting exploring the hidden dimensions of identity. Rich layers of acrylic and texture reveal the complexity beneath the surface of every person.',
      images: JSON.stringify(['/images/artworks/artwork-1.jpg']),
      category: 'PAINTING',
      medium: 'mixed_media',
      dimensions: JSON.stringify({ width: 40, height: 40, unit: 'in' }),
      year: 2024,
      status: 'AVAILABLE',
      price: 8500,
      priceOnInquiry: false,
      collectionId: 'col-1',
      tags: JSON.stringify(['abstract', 'figurative', 'textural', 'soul']),
      featured: true,
      framing: 'Gallery wrapped canvas, ready to hang',
      certificate: 'true',
    },
    {
      id: 'art-2',
      title: 'Eternal Beauty',
      slug: 'eternal-beauty',
      description: 'A stunning portrait celebrating timeless feminine grace. Bold color and flowing composition create a sense of movement and enduring elegance.',
      images: JSON.stringify(['/images/artworks/artwork-2.jpg']),
      category: 'PAINTING',
      medium: 'acrylic',
      dimensions: JSON.stringify({ width: 36, height: 48, unit: 'in' }),
      year: 2024,
      status: 'AVAILABLE',
      price: 9200,
      priceOnInquiry: false,
      collectionId: 'col-1',
      tags: JSON.stringify(['figurative', 'portrait', 'beauty', 'bold']),
      featured: true,
      framing: 'Floating frame in brushed gold',
      certificate: 'true',
    },
    {
      id: 'art-3',
      title: 'Fancy Girl',
      slug: 'fancy-girl',
      description: 'A vibrant celebration of femininity and confidence. Rich colors and expressive forms create a powerful portrait that commands attention and radiates joy.',
      images: JSON.stringify(['/images/artworks/artwork-3.jpg']),
      category: 'PAINTING',
      medium: 'acrylic',
      dimensions: JSON.stringify({ width: 30, height: 40, unit: 'in' }),
      year: 2023,
      status: 'SOLD',
      priceOnInquiry: true,
      collectionId: 'col-1',
      tags: JSON.stringify(['figurative', 'portrait', 'vibrant', 'woman']),
      featured: true,
      certificate: 'true',
    },
    {
      id: 'art-4',
      title: 'Tomorrow Is Another Day',
      slug: 'tomorrow-is-another-day',
      description: 'An optimistic and vibrant composition reflecting hope and resilience. The interplay of warm tones and dynamic brushwork speaks to the promise of new beginnings.',
      images: JSON.stringify(['/images/artworks/artwork-4.jpg']),
      category: 'PAINTING',
      medium: 'mixed_media',
      dimensions: JSON.stringify({ width: 36, height: 36, unit: 'in' }),
      year: 2024,
      status: 'AVAILABLE',
      price: 7800,
      priceOnInquiry: false,
      collectionId: 'col-3',
      tags: JSON.stringify(['abstract', 'hope', 'colorful', 'emotion']),
      featured: false,
      framing: 'Gallery wrapped canvas',
      certificate: 'true',
    },
    {
      id: 'art-5',
      title: "Today's Woman",
      slug: 'todays-woman',
      description: 'A bold contemporary portrait honoring the strength and complexity of modern womanhood. Layers of acrylic and mixed media build a compelling narrative of empowerment.',
      images: JSON.stringify(['/images/artworks/artwork-5.jpg']),
      category: 'PAINTING',
      medium: 'acrylic',
      dimensions: JSON.stringify({ width: 40, height: 50, unit: 'in' }),
      year: 2024,
      status: 'AVAILABLE',
      price: 11000,
      priceOnInquiry: false,
      collectionId: 'col-1',
      tags: JSON.stringify(['figurative', 'woman', 'contemporary', 'strength']),
      featured: true,
      framing: 'Floating frame in matte black',
      certificate: 'true',
    },
    {
      id: 'art-6',
      title: 'Steadfast',
      slug: 'steadfast',
      description: 'A commanding piece that captures unwavering determination and inner fortitude. Deep tones and textured surfaces create a sense of grounded strength.',
      images: JSON.stringify(['/images/artworks/artwork-6.jpg']),
      category: 'PAINTING',
      medium: 'mixed_media',
      dimensions: JSON.stringify({ width: 36, height: 48, unit: 'in' }),
      year: 2024,
      status: 'SOLD',
      priceOnInquiry: true,
      collectionId: 'col-1',
      tags: JSON.stringify(['figurative', 'strength', 'bold', 'textural']),
      featured: false,
      certificate: 'true',
    },
    {
      id: 'art-7',
      title: 'Mask Girl',
      slug: 'mask-girl',
      description: 'An evocative exploration of identity and concealment. The mask motif recurs throughout Mona Niko\'s work, questioning the faces we present to the world.',
      images: JSON.stringify(['/images/artworks/artwork-7.jpg']),
      category: 'PAINTING',
      medium: 'acrylic',
      dimensions: JSON.stringify({ width: 30, height: 40, unit: 'in' }),
      year: 2023,
      status: 'AVAILABLE',
      price: 7500,
      priceOnInquiry: false,
      collectionId: 'col-1',
      tags: JSON.stringify(['figurative', 'mask', 'identity', 'woman']),
      featured: true,
      framing: 'Gallery wrapped canvas',
      certificate: 'true',
    },
    {
      id: 'art-8',
      title: 'Three Women',
      slug: 'three-women',
      description: 'A powerful triptych-style composition depicting three female figures, each representing a different facet of womanhood — strength, grace, and wisdom.',
      images: JSON.stringify(['/images/artworks/artwork-8.jpg']),
      category: 'PAINTING',
      medium: 'mixed_media',
      dimensions: JSON.stringify({ width: 60, height: 40, unit: 'in' }),
      year: 2024,
      status: 'AVAILABLE',
      price: 14500,
      priceOnInquiry: false,
      collectionId: 'col-1',
      tags: JSON.stringify(['figurative', 'women', 'large-scale', 'narrative']),
      featured: true,
      framing: 'Gallery wrapped canvas, ready to hang',
      certificate: 'true',
    },
    {
      id: 'art-9',
      title: 'Old Ghajar',
      slug: 'old-ghajar',
      description: 'A richly detailed work drawing from the opulence and mystique of the Qajar dynasty. Traditional Persian motifs merge with contemporary expression in a tribute to cultural heritage.',
      images: JSON.stringify(['/images/artworks/artwork-1.jpg']),
      category: 'PAINTING',
      medium: 'mixed_media',
      dimensions: JSON.stringify({ width: 36, height: 48, unit: 'in' }),
      year: 2023,
      status: 'SOLD',
      priceOnInquiry: true,
      collectionId: 'col-2',
      tags: JSON.stringify(['persian', 'heritage', 'qajar', 'figurative']),
      featured: false,
      certificate: 'true',
    },
    {
      id: 'art-10',
      title: 'Woman Mask',
      slug: 'woman-mask',
      description: 'A striking portrayal of feminine mystery. The mask becomes a symbol of the layers every woman carries — strength hidden behind beauty, vulnerability guarded by poise.',
      images: JSON.stringify(['/images/artworks/artwork-2.jpg']),
      category: 'PAINTING',
      medium: 'acrylic',
      dimensions: JSON.stringify({ width: 30, height: 40, unit: 'in' }),
      year: 2024,
      status: 'AVAILABLE',
      price: 6800,
      priceOnInquiry: false,
      collectionId: 'col-1',
      tags: JSON.stringify(['figurative', 'mask', 'woman', 'mystery']),
      featured: false,
      framing: 'Gallery wrapped canvas',
      certificate: 'true',
    },
    {
      id: 'art-11',
      title: 'Secret',
      slug: 'secret',
      description: 'An intimate and enigmatic work where hidden shapes and whispered colors invite the viewer to look deeper. Layers of paint conceal and reveal in equal measure.',
      images: JSON.stringify(['/images/artworks/artwork-3.jpg']),
      category: 'MIXED_MEDIA',
      medium: 'mixed_media',
      dimensions: JSON.stringify({ width: 30, height: 30, unit: 'in' }),
      year: 2024,
      status: 'AVAILABLE',
      price: 5500,
      priceOnInquiry: false,
      collectionId: 'col-3',
      tags: JSON.stringify(['abstract', 'mystery', 'textural', 'intimate']),
      featured: false,
      framing: 'Shadow box frame',
      certificate: 'true',
    },
    {
      id: 'art-12',
      title: 'Super Woman',
      slug: 'super-woman',
      description: 'A bold and empowering piece celebrating the extraordinary strength of women. Vivid hues and dynamic composition radiate power and confidence.',
      images: JSON.stringify(['/images/artworks/artwork-4.jpg']),
      category: 'PAINTING',
      medium: 'acrylic',
      dimensions: JSON.stringify({ width: 40, height: 50, unit: 'in' }),
      year: 2024,
      status: 'AVAILABLE',
      price: 9500,
      priceOnInquiry: false,
      collectionId: 'col-1',
      tags: JSON.stringify(['figurative', 'woman', 'power', 'colorful']),
      featured: true,
      framing: 'Floating frame in brushed gold',
      certificate: 'true',
    },
    {
      id: 'art-13',
      title: 'Ghajar Woman Man',
      slug: 'ghajar-woman-man',
      description: 'A dialogue between masculine and feminine energies inspired by Qajar-era portraiture. Traditional iconography is reinterpreted through a contemporary lens.',
      images: JSON.stringify(['/images/artworks/artwork-5.jpg']),
      category: 'PAINTING',
      medium: 'mixed_media',
      dimensions: JSON.stringify({ width: 48, height: 36, unit: 'in' }),
      year: 2023,
      status: 'SOLD',
      priceOnInquiry: true,
      collectionId: 'col-2',
      tags: JSON.stringify(['persian', 'heritage', 'qajar', 'duality']),
      featured: false,
      certificate: 'true',
    },
    {
      id: 'art-14',
      title: 'Waiting',
      slug: 'waiting',
      description: 'A contemplative piece capturing the quiet tension of anticipation. Soft tones and restrained brushwork convey both patience and longing.',
      images: JSON.stringify(['/images/artworks/artwork-6.jpg']),
      category: 'PAINTING',
      medium: 'acrylic',
      dimensions: JSON.stringify({ width: 36, height: 36, unit: 'in' }),
      year: 2024,
      status: 'AVAILABLE',
      price: 6200,
      priceOnInquiry: false,
      collectionId: 'col-3',
      tags: JSON.stringify(['figurative', 'contemplative', 'emotion', 'subtle']),
      featured: false,
      framing: 'Minimal black frame',
      certificate: 'true',
    },
    {
      id: 'art-15',
      title: 'Salsa',
      slug: 'salsa',
      description: 'An explosion of movement and rhythm captured on canvas. Warm reds and oranges swirl in a passionate dance that pulses with energy and life.',
      images: JSON.stringify(['/images/artworks/artwork-7.jpg']),
      category: 'PAINTING',
      medium: 'acrylic',
      dimensions: JSON.stringify({ width: 40, height: 40, unit: 'in' }),
      year: 2024,
      status: 'ON_EXHIBITION',
      priceOnInquiry: true,
      tags: JSON.stringify(['abstract', 'dance', 'movement', 'red']),
      featured: true,
      certificate: 'true',
    },
    {
      id: 'art-16',
      title: 'Woman Naghsh Eslimi',
      slug: 'woman-naghsh-eslimi',
      description: 'A masterful fusion of traditional Persian arabesque patterns with a modern female figure. Eslimi motifs weave around the subject creating a tapestry of cultural identity.',
      images: JSON.stringify(['/images/artworks/artwork-8.jpg']),
      category: 'MIXED_MEDIA',
      medium: 'mixed_media',
      dimensions: JSON.stringify({ width: 36, height: 48, unit: 'in' }),
      year: 2023,
      status: 'SOLD',
      priceOnInquiry: true,
      collectionId: 'col-2',
      tags: JSON.stringify(['persian', 'eslimi', 'figurative', 'ornamental']),
      featured: false,
      certificate: 'true',
    },
    {
      id: 'art-17',
      title: 'In Hands',
      slug: 'in-hands',
      description: 'A tender and symbolic work focusing on the expressive power of hands — holding, releasing, protecting. The gesture speaks volumes about connection and care.',
      images: JSON.stringify(['/images/artworks/artwork-1.jpg']),
      category: 'PAINTING',
      medium: 'acrylic',
      dimensions: JSON.stringify({ width: 30, height: 40, unit: 'in' }),
      year: 2024,
      status: 'AVAILABLE',
      price: 5800,
      priceOnInquiry: false,
      collectionId: 'col-3',
      tags: JSON.stringify(['figurative', 'hands', 'emotion', 'symbolic']),
      featured: false,
      framing: 'Gallery wrapped canvas',
      certificate: 'true',
    },
    {
      id: 'art-18',
      title: 'In Dream',
      slug: 'in-dream',
      description: 'A surreal and ethereal composition where reality dissolves into dreamscape. Soft, flowing forms and luminous color evoke the liminal space between sleep and waking.',
      images: JSON.stringify(['/images/artworks/artwork-2.jpg']),
      category: 'PAINTING',
      medium: 'mixed_media',
      dimensions: JSON.stringify({ width: 40, height: 40, unit: 'in' }),
      year: 2024,
      status: 'AVAILABLE',
      price: 7200,
      priceOnInquiry: false,
      collectionId: 'col-3',
      tags: JSON.stringify(['abstract', 'dream', 'surreal', 'ethereal']),
      featured: false,
      framing: 'Floating frame in white',
      certificate: 'true',
    },
    {
      id: 'art-19',
      title: 'Freedom',
      slug: 'freedom',
      description: 'A soaring, liberating work that captures the exhilaration of breaking free. Dynamic lines and expansive composition convey unbounded possibility.',
      images: JSON.stringify(['/images/artworks/artwork-3.jpg']),
      category: 'PAINTING',
      medium: 'acrylic',
      dimensions: JSON.stringify({ width: 48, height: 36, unit: 'in' }),
      year: 2024,
      status: 'AVAILABLE',
      price: 10500,
      priceOnInquiry: false,
      collectionId: 'col-3',
      tags: JSON.stringify(['abstract', 'freedom', 'dynamic', 'movement']),
      featured: true,
      framing: 'Gallery wrapped canvas, ready to hang',
      certificate: 'true',
    },
    {
      id: 'art-20',
      title: 'Deep In Love',
      slug: 'deep-in-love',
      description: 'An intensely romantic piece where color and form intertwine in a visual expression of deep emotional connection. Warm tones envelop the viewer in intimate passion.',
      images: JSON.stringify(['/images/artworks/artwork-4.jpg']),
      category: 'PAINTING',
      medium: 'acrylic',
      dimensions: JSON.stringify({ width: 36, height: 48, unit: 'in' }),
      year: 2024,
      status: 'AVAILABLE',
      price: 8200,
      priceOnInquiry: false,
      collectionId: 'col-3',
      tags: JSON.stringify(['figurative', 'love', 'romantic', 'emotion']),
      featured: false,
      framing: 'Floating frame in brushed gold',
      certificate: 'true',
    },
    {
      id: 'art-21',
      title: 'Dancing Woman',
      slug: 'dancing-woman',
      description: 'Fluid movement captured in paint — a dancer mid-motion, where the boundary between figure and abstraction dissolves into pure kinetic energy.',
      images: JSON.stringify(['/images/artworks/artwork-5.jpg']),
      category: 'PAINTING',
      medium: 'acrylic',
      dimensions: JSON.stringify({ width: 36, height: 48, unit: 'in' }),
      year: 2024,
      status: 'ON_EXHIBITION',
      priceOnInquiry: true,
      tags: JSON.stringify(['figurative', 'dance', 'movement', 'woman']),
      featured: false,
      certificate: 'true',
    },
    {
      id: 'art-22',
      title: 'Conscience',
      slug: 'conscience',
      description: 'A thought-provoking piece that delves into the inner moral compass. Contrasting light and shadow create a visual tension reflecting the complexity of right and wrong.',
      images: JSON.stringify(['/images/artworks/artwork-6.jpg']),
      category: 'PAINTING',
      medium: 'mixed_media',
      dimensions: JSON.stringify({ width: 30, height: 40, unit: 'in' }),
      year: 2024,
      status: 'AVAILABLE',
      price: 6500,
      priceOnInquiry: false,
      collectionId: 'col-3',
      tags: JSON.stringify(['figurative', 'introspective', 'moral', 'contrast']),
      featured: false,
      framing: 'Gallery wrapped canvas',
      certificate: 'true',
    },
    {
      id: 'art-23',
      title: 'Audrey Hepburn',
      slug: 'audrey-hepburn',
      description: "A contemporary reimagining of Hollywood's most iconic beauty. Mona Niko's signature style transforms the classic portrait into a vibrant celebration of timeless elegance.",
      images: JSON.stringify(['/images/artworks/artwork-7.jpg']),
      category: 'PAINTING',
      medium: 'acrylic',
      dimensions: JSON.stringify({ width: 30, height: 40, unit: 'in' }),
      year: 2023,
      status: 'SOLD',
      priceOnInquiry: true,
      collectionId: 'col-1',
      tags: JSON.stringify(['figurative', 'portrait', 'icon', 'pop']),
      featured: false,
      certificate: 'true',
    },
    {
      id: 'art-24',
      title: 'Tiger',
      slug: 'tiger',
      description: 'A fierce and majestic portrayal of raw power. Bold strokes and vivid coloring bring the tiger to life with an intensity that commands the room.',
      images: JSON.stringify(['/images/artworks/artwork-8.jpg']),
      category: 'PAINTING',
      medium: 'acrylic',
      dimensions: JSON.stringify({ width: 40, height: 40, unit: 'in' }),
      year: 2024,
      status: 'AVAILABLE',
      price: 8800,
      priceOnInquiry: false,
      tags: JSON.stringify(['animal', 'tiger', 'power', 'bold']),
      featured: false,
      framing: 'Gallery wrapped canvas',
      certificate: 'true',
    },
    {
      id: 'art-25',
      title: 'Golden Girl',
      slug: 'golden-girl',
      description: 'A luminous portrait bathed in gold tones. The figure radiates warmth and confidence, embodying the richness of self-assurance and inner glow.',
      images: JSON.stringify(['/images/artworks/artwork-1.jpg']),
      category: 'PAINTING',
      medium: 'mixed_media',
      dimensions: JSON.stringify({ width: 36, height: 48, unit: 'in' }),
      year: 2024,
      status: 'AVAILABLE',
      price: 9800,
      priceOnInquiry: false,
      collectionId: 'col-1',
      tags: JSON.stringify(['figurative', 'gold', 'portrait', 'luminous']),
      featured: true,
      framing: 'Floating frame in brushed gold',
      certificate: 'true',
    },
    {
      id: 'art-26',
      title: 'Hands On Face',
      slug: 'hands-on-face',
      description: 'A deeply emotional composition where hands frame and partially conceal the face — a universal gesture of vulnerability, contemplation, and raw feeling.',
      images: JSON.stringify(['/images/artworks/artwork-2.jpg']),
      category: 'PAINTING',
      medium: 'acrylic',
      dimensions: JSON.stringify({ width: 30, height: 40, unit: 'in' }),
      year: 2024,
      status: 'AVAILABLE',
      price: 7200,
      priceOnInquiry: false,
      collectionId: 'col-3',
      tags: JSON.stringify(['figurative', 'hands', 'emotion', 'portrait']),
      featured: false,
      framing: 'Gallery wrapped canvas',
      certificate: 'true',
    },
    {
      id: 'art-27',
      title: 'The Bird of Luck',
      slug: 'the-bird-of-luck',
      description: 'A symbolic and ornate work featuring a bird as a harbinger of fortune and hope. Persian artistic traditions inform the rich patterning and vivid palette.',
      images: JSON.stringify(['/images/artworks/artwork-3.jpg']),
      category: 'MIXED_MEDIA',
      medium: 'mixed_media',
      dimensions: JSON.stringify({ width: 30, height: 30, unit: 'in' }),
      year: 2024,
      status: 'AVAILABLE',
      price: 5800,
      priceOnInquiry: false,
      collectionId: 'col-2',
      tags: JSON.stringify(['symbolic', 'bird', 'persian', 'fortune']),
      featured: false,
      framing: 'Shadow box frame',
      certificate: 'true',
    },
    {
      id: 'art-28',
      title: 'Love',
      slug: 'love',
      description: 'A pure and powerful visual statement on love in all its forms. Warm, enveloping colors and flowing shapes create a sense of tenderness and infinite connection.',
      images: JSON.stringify(['/images/artworks/artwork-4.jpg']),
      category: 'PAINTING',
      medium: 'acrylic',
      dimensions: JSON.stringify({ width: 36, height: 36, unit: 'in' }),
      year: 2024,
      status: 'AVAILABLE',
      price: 6500,
      priceOnInquiry: false,
      collectionId: 'col-3',
      tags: JSON.stringify(['abstract', 'love', 'emotion', 'warmth']),
      featured: false,
      framing: 'Gallery wrapped canvas',
      certificate: 'true',
    },
    {
      id: 'art-29',
      title: 'Green Beauty',
      slug: 'green-beauty',
      description: 'A lush and captivating portrait where emerald and jade tones create an atmosphere of natural elegance. The subject emerges from verdant depths like a living jewel.',
      images: JSON.stringify(['/images/artworks/artwork-5.jpg']),
      category: 'PAINTING',
      medium: 'acrylic',
      dimensions: JSON.stringify({ width: 30, height: 40, unit: 'in' }),
      year: 2024,
      status: 'AVAILABLE',
      price: 7000,
      priceOnInquiry: false,
      tags: JSON.stringify(['figurative', 'portrait', 'green', 'beauty']),
      featured: false,
      framing: 'Floating frame in matte black',
      certificate: 'true',
    },
    {
      id: 'art-30',
      title: 'Meditation',
      slug: 'meditation',
      description: 'A serene and calming work that invites the viewer into a state of inner stillness. Soft transitions and minimal forms create a visual mantra of peace.',
      images: JSON.stringify(['/images/artworks/artwork-6.jpg']),
      category: 'PAINTING',
      medium: 'acrylic',
      dimensions: JSON.stringify({ width: 36, height: 36, unit: 'in' }),
      year: 2025,
      status: 'AVAILABLE',
      price: 6800,
      priceOnInquiry: false,
      collectionId: 'col-3',
      tags: JSON.stringify(['abstract', 'meditation', 'calm', 'minimal']),
      featured: false,
      framing: 'Gallery wrapped canvas',
      certificate: 'true',
    },
  ];

  for (const art of artworksData) {
    await prisma.artwork.create({ data: art });
  }
  console.log(`  Created ${artworksData.length} artworks.`);

  // ─── Products ──────────────────────────────────────────────
  console.log('Seeding products...');

  const productsData = [
    {
      id: 'prod-1',
      title: 'Freedom Phone Case',
      slug: 'freedom-phone-case',
      description: "Protect your phone in style with this premium hard-shell case featuring Mona Niko's 'Freedom' artwork. Slim profile with full port access.",
      images: JSON.stringify(['/images/artworks/artwork-3.jpg']),
      type: 'MERCH_PHONE_CASE',
      basePrice: 35,
      artworkId: 'art-19',
      featured: true,
      tags: JSON.stringify(['phone-case', 'merch', 'freedom']),
      variants: [
        { id: 'var-1', name: 'iPhone 14/15', price: 35, stock: 50 },
        { id: 'var-2', name: 'iPhone 14/15 Pro Max', price: 35, stock: 40 },
        { id: 'var-3', name: 'Samsung Galaxy S24', price: 35, stock: 30 },
      ],
    },
    {
      id: 'prod-2',
      title: 'Golden Girl Phone Case',
      slug: 'golden-girl-phone-case',
      description: "A stunning phone case featuring the luminous 'Golden Girl' artwork by Mona Niko. Durable polycarbonate shell with vibrant, fade-resistant printing.",
      images: JSON.stringify(['/images/artworks/artwork-1.jpg']),
      type: 'MERCH_PHONE_CASE',
      basePrice: 35,
      artworkId: 'art-25',
      featured: false,
      tags: JSON.stringify(['phone-case', 'merch', 'golden-girl']),
      variants: [
        { id: 'var-4', name: 'iPhone 14/15', price: 35, stock: 45 },
        { id: 'var-5', name: 'iPhone 14/15 Pro Max', price: 35, stock: 35 },
        { id: 'var-6', name: 'Samsung Galaxy S24', price: 35, stock: 25 },
      ],
    },
    {
      id: 'prod-3',
      title: 'Hands On Face Phone Case',
      slug: 'hands-on-face-phone-case',
      description: "Carry Mona Niko's emotionally powerful 'Hands On Face' artwork everywhere you go. Premium quality case with scratch-resistant finish.",
      images: JSON.stringify(['/images/artworks/artwork-2.jpg']),
      type: 'MERCH_PHONE_CASE',
      basePrice: 35,
      artworkId: 'art-26',
      featured: false,
      tags: JSON.stringify(['phone-case', 'merch', 'hands-on-face']),
      variants: [
        { id: 'var-7', name: 'iPhone 14/15', price: 35, stock: 40 },
        { id: 'var-8', name: 'iPhone 14/15 Pro Max', price: 35, stock: 30 },
      ],
    },
    {
      id: 'prod-4',
      title: 'Super Woman Art Cushion',
      slug: 'super-woman-art-cushion',
      description: "Transform your living space with this luxurious art cushion featuring Mona Niko's empowering 'Super Woman' design. Double-sided printing on premium fabric.",
      images: JSON.stringify(['/images/artworks/artwork-4.jpg']),
      type: 'MERCH_CUSHION',
      basePrice: 55,
      artworkId: 'art-12',
      featured: true,
      tags: JSON.stringify(['cushion', 'merch', 'super-woman', 'home-decor']),
      variants: [
        { id: 'var-9', name: '18" x 18"', price: 55, dimensions: '18" x 18"', stock: 30 },
        { id: 'var-10', name: '22" x 22"', price: 65, dimensions: '22" x 22"', stock: 20 },
      ],
    },
    {
      id: 'prod-5',
      title: 'Audrey Hepburn Art Cushion',
      slug: 'audrey-hepburn-art-cushion',
      description: "Iconic style meets contemporary art in this beautiful cushion featuring Mona Niko's reimagined Audrey Hepburn portrait. Soft velvet-like fabric with hidden zipper.",
      images: JSON.stringify(['/images/artworks/artwork-7.jpg']),
      type: 'MERCH_CUSHION',
      basePrice: 55,
      artworkId: 'art-23',
      featured: false,
      tags: JSON.stringify(['cushion', 'merch', 'audrey-hepburn', 'home-decor']),
      variants: [
        { id: 'var-11', name: '18" x 18"', price: 55, dimensions: '18" x 18"', stock: 25 },
        { id: 'var-12', name: '22" x 22"', price: 65, dimensions: '22" x 22"', stock: 15 },
      ],
    },
    {
      id: 'prod-6',
      title: 'Conscience Art Cushion',
      slug: 'conscience-art-cushion',
      description: "Add depth and artistry to your space with this thought-provoking cushion from Mona Niko's 'Conscience' series.",
      images: JSON.stringify(['/images/artworks/artwork-6.jpg']),
      type: 'MERCH_CUSHION',
      basePrice: 55,
      artworkId: 'art-22',
      featured: false,
      tags: JSON.stringify(['cushion', 'merch', 'conscience', 'home-decor']),
      variants: [
        { id: 'var-13', name: '18" x 18"', price: 55, dimensions: '18" x 18"', stock: 20 },
        { id: 'var-14', name: '22" x 22"', price: 65, dimensions: '22" x 22"', stock: 15 },
      ],
    },
    {
      id: 'prod-7',
      title: "Hands On Face Men's T-Shirt",
      slug: 'hands-on-face-mens-tshirt',
      description: "Premium cotton men's t-shirt featuring Mona Niko's iconic 'Hands On Face' artwork. Pre-shrunk fabric with museum-quality DTG printing.",
      images: JSON.stringify(['/images/artworks/artwork-2.jpg']),
      type: 'MERCH_TSHIRT',
      basePrice: 45,
      artworkId: 'art-26',
      featured: true,
      tags: JSON.stringify(['tshirt', 'men', 'merch', 'hands-on-face']),
      variants: [
        { id: 'var-15', name: 'S', price: 45, stock: 25 },
        { id: 'var-16', name: 'M', price: 45, stock: 30 },
        { id: 'var-17', name: 'L', price: 45, stock: 30 },
        { id: 'var-18', name: 'XL', price: 45, stock: 20 },
      ],
    },
    {
      id: 'prod-8',
      title: "Tiger Men's T-Shirt",
      slug: 'tiger-mens-tshirt',
      description: "Make a bold statement with this premium men's t-shirt featuring Mona Niko's powerful 'Tiger' artwork. 100% ring-spun cotton.",
      images: JSON.stringify(['/images/artworks/artwork-8.jpg']),
      type: 'MERCH_TSHIRT',
      basePrice: 45,
      artworkId: 'art-24',
      featured: false,
      tags: JSON.stringify(['tshirt', 'men', 'merch', 'tiger']),
      variants: [
        { id: 'var-19', name: 'S', price: 45, stock: 20 },
        { id: 'var-20', name: 'M', price: 45, stock: 25 },
        { id: 'var-21', name: 'L', price: 45, stock: 25 },
        { id: 'var-22', name: 'XL', price: 45, stock: 15 },
      ],
    },
    {
      id: 'prod-9',
      title: "Freedom Men's T-Shirt",
      slug: 'freedom-mens-tshirt',
      description: "Wear your freedom proudly with this premium men's t-shirt featuring Mona Niko's dynamic 'Freedom' artwork. Soft-hand feel with vibrant, washable print.",
      images: JSON.stringify(['/images/artworks/artwork-3.jpg']),
      type: 'MERCH_TSHIRT',
      basePrice: 45,
      artworkId: 'art-19',
      featured: false,
      tags: JSON.stringify(['tshirt', 'men', 'merch', 'freedom']),
      variants: [
        { id: 'var-23', name: 'S', price: 45, stock: 20 },
        { id: 'var-24', name: 'M', price: 45, stock: 30 },
        { id: 'var-25', name: 'L', price: 45, stock: 25 },
        { id: 'var-26', name: 'XL', price: 45, stock: 15 },
      ],
    },
    {
      id: 'prod-10',
      title: 'Originality Silk Tie',
      slug: 'originality-silk-tie',
      description: "A wearable work of art — this premium silk tie features a detail from Mona Niko's 'Originality' painting. Perfect for collectors who wear their passion.",
      images: JSON.stringify(['/images/artworks/artwork-1.jpg']),
      type: 'MERCH_TIE',
      basePrice: 75,
      featured: false,
      tags: JSON.stringify(['tie', 'merch', 'originality', 'silk']),
      variants: [
        { id: 'var-27', name: 'Standard', price: 75, stock: 30 },
      ],
    },
    {
      id: 'prod-11',
      title: 'Love Silk Tie',
      slug: 'love-silk-tie',
      description: "Express yourself with this elegant silk tie featuring colors and patterns from Mona Niko's 'Love' painting. Handcrafted from 100% Italian silk.",
      images: JSON.stringify(['/images/artworks/artwork-4.jpg']),
      type: 'MERCH_TIE',
      basePrice: 75,
      artworkId: 'art-28',
      featured: false,
      tags: JSON.stringify(['tie', 'merch', 'love', 'silk']),
      variants: [
        { id: 'var-28', name: 'Standard', price: 75, stock: 25 },
      ],
    },
    {
      id: 'prod-12',
      title: 'Hands On Face Laptop Case',
      slug: 'hands-on-face-laptop-case',
      description: "Protect your laptop with art. This premium neoprene case features Mona Niko's emotionally charged 'Hands On Face' design with a soft interior lining.",
      images: JSON.stringify(['/images/artworks/artwork-2.jpg']),
      type: 'MERCH_LAPTOP_CASE',
      basePrice: 55,
      artworkId: 'art-26',
      featured: true,
      tags: JSON.stringify(['laptop-case', 'merch', 'hands-on-face']),
      variants: [
        { id: 'var-29', name: '13"', price: 55, stock: 20 },
        { id: 'var-30', name: '15"', price: 60, stock: 20 },
        { id: 'var-31', name: '16"', price: 65, stock: 15 },
      ],
    },
    {
      id: 'prod-13',
      title: 'Freedom Laptop Case',
      slug: 'freedom-laptop-case',
      description: "Carry your creativity with this stunning laptop case featuring Mona Niko's 'Freedom' artwork. Water-resistant exterior with padded protection.",
      images: JSON.stringify(['/images/artworks/artwork-3.jpg']),
      type: 'MERCH_LAPTOP_CASE',
      basePrice: 55,
      artworkId: 'art-19',
      featured: false,
      tags: JSON.stringify(['laptop-case', 'merch', 'freedom']),
      variants: [
        { id: 'var-32', name: '13"', price: 55, stock: 18 },
        { id: 'var-33', name: '15"', price: 60, stock: 15 },
        { id: 'var-34', name: '16"', price: 65, stock: 12 },
      ],
    },
    {
      id: 'prod-14',
      title: 'Freedom Suitcase',
      slug: 'freedom-suitcase',
      description: "Travel in style with this durable hard-shell suitcase featuring Mona Niko's 'Freedom' artwork. TSA-approved lock, 360-degree spinner wheels, and expandable design.",
      images: JSON.stringify(['/images/artworks/artwork-3.jpg']),
      type: 'MERCH_SUITCASE',
      basePrice: 189,
      artworkId: 'art-19',
      featured: true,
      tags: JSON.stringify(['suitcase', 'merch', 'freedom', 'travel']),
      variants: [
        { id: 'var-35', name: 'Carry-On (20")', price: 189, stock: 10 },
        { id: 'var-36', name: 'Medium (24")', price: 229, stock: 8 },
        { id: 'var-37', name: 'Large (28")', price: 269, stock: 6 },
      ],
    },
    {
      id: 'prod-15',
      title: 'Hands On Face Suitcase',
      slug: 'hands-on-face-suitcase',
      description: "Make a statement at baggage claim with this eye-catching suitcase featuring Mona Niko's 'Hands On Face' artwork. Hard-shell polycarbonate with telescoping handle.",
      images: JSON.stringify(['/images/artworks/artwork-2.jpg']),
      type: 'MERCH_SUITCASE',
      basePrice: 189,
      artworkId: 'art-26',
      featured: false,
      tags: JSON.stringify(['suitcase', 'merch', 'hands-on-face', 'travel']),
      variants: [
        { id: 'var-38', name: 'Carry-On (20")', price: 189, stock: 8 },
        { id: 'var-39', name: 'Medium (24")', price: 229, stock: 6 },
        { id: 'var-40', name: 'Large (28")', price: 269, stock: 5 },
      ],
    },
    {
      id: 'prod-16',
      title: 'Freedom Art Leggings',
      slug: 'freedom-art-leggings',
      description: "Move freely in these high-performance art leggings featuring Mona Niko's 'Freedom' design. Four-way stretch fabric with moisture-wicking technology.",
      images: JSON.stringify(['/images/artworks/artwork-3.jpg']),
      type: 'MERCH_LEGGINGS',
      basePrice: 65,
      artworkId: 'art-19',
      featured: false,
      tags: JSON.stringify(['leggings', 'merch', 'freedom', 'activewear']),
      variants: [
        { id: 'var-41', name: 'XS', price: 65, stock: 15 },
        { id: 'var-42', name: 'S', price: 65, stock: 20 },
        { id: 'var-43', name: 'M', price: 65, stock: 25 },
        { id: 'var-44', name: 'L', price: 65, stock: 20 },
        { id: 'var-45', name: 'XL', price: 65, stock: 10 },
      ],
    },
    {
      id: 'prod-17',
      title: 'Golden Girl Sweatshirt',
      slug: 'golden-girl-sweatshirt',
      description: "Stay warm in wearable art with this premium fleece-lined sweatshirt featuring Mona Niko's radiant 'Golden Girl' design. Unisex fit with ribbed cuffs.",
      images: JSON.stringify(['/images/artworks/artwork-1.jpg']),
      type: 'MERCH_SWEATSHIRT',
      basePrice: 75,
      artworkId: 'art-25',
      featured: true,
      tags: JSON.stringify(['sweatshirt', 'merch', 'golden-girl', 'apparel']),
      variants: [
        { id: 'var-46', name: 'S', price: 75, stock: 20 },
        { id: 'var-47', name: 'M', price: 75, stock: 25 },
        { id: 'var-48', name: 'L', price: 75, stock: 25 },
        { id: 'var-49', name: 'XL', price: 75, stock: 15 },
      ],
    },
    {
      id: 'prod-18',
      title: 'Layers of the Soul — Limited Edition Print',
      slug: 'layers-of-the-soul-print',
      description: 'Museum-quality giclee print on archival paper. Limited edition of 50, hand-signed and numbered by Mona Niko. Certificate of authenticity included.',
      images: JSON.stringify(['/images/artworks/artwork-1.jpg']),
      type: 'PRINT',
      basePrice: 250,
      artworkId: 'art-1',
      featured: true,
      tags: JSON.stringify(['print', 'limited-edition', 'layers-of-the-soul']),
      variants: [
        { id: 'var-50', name: '16" x 16"', price: 250, dimensions: '16" x 16"', stock: 40 },
        { id: 'var-51', name: '24" x 24"', price: 450, dimensions: '24" x 24"', stock: 25 },
        { id: 'var-52', name: '30" x 30"', price: 750, dimensions: '30" x 30"', stock: 15 },
      ],
    },
    {
      id: 'prod-19',
      title: 'Freedom — Limited Edition Print',
      slug: 'freedom-print',
      description: 'Museum-quality giclee print on archival cotton rag paper. Limited edition of 30, hand-signed and numbered by the artist.',
      images: JSON.stringify(['/images/artworks/artwork-3.jpg']),
      type: 'PRINT',
      basePrice: 350,
      artworkId: 'art-19',
      featured: true,
      tags: JSON.stringify(['print', 'limited-edition', 'freedom']),
      variants: [
        { id: 'var-53', name: '18" x 24"', price: 350, dimensions: '18" x 24"', stock: 20 },
        { id: 'var-54', name: '24" x 32"', price: 550, dimensions: '24" x 32"', stock: 12 },
      ],
    },
    {
      id: 'prod-20',
      title: 'Golden Girl — Limited Edition Print',
      slug: 'golden-girl-print',
      description: 'Museum-quality giclee print with gold foil accents on archival paper. Limited edition of 25, hand-signed by Mona Niko.',
      images: JSON.stringify(['/images/artworks/artwork-1.jpg']),
      type: 'PRINT',
      basePrice: 380,
      artworkId: 'art-25',
      featured: false,
      tags: JSON.stringify(['print', 'limited-edition', 'golden-girl', 'gold-foil']),
      variants: [
        { id: 'var-55', name: '20" x 20"', price: 380, dimensions: '20" x 20"', stock: 18 },
        { id: 'var-56', name: '30" x 30"', price: 680, dimensions: '30" x 30"', stock: 10 },
      ],
    },
    {
      id: 'prod-21',
      title: 'Tiny Colorful Jacket',
      slug: 'tiny-colorful-jacket',
      description: "A vibrant, one-of-a-kind jacket from Mona Niko's Designers Collection. Hand-embellished with artistic details that make each piece a wearable work of art.",
      images: JSON.stringify(['/images/artworks/artwork-4.jpg']),
      type: 'DESIGNERS_COLLECTION',
      basePrice: 200,
      featured: true,
      tags: JSON.stringify(['jacket', 'designers-collection', 'colorful', 'clothing']),
      variants: [
        { id: 'var-57', name: 'S', price: 200, stock: 3 },
        { id: 'var-58', name: 'M', price: 200, stock: 4 },
        { id: 'var-59', name: 'L', price: 200, stock: 3 },
      ],
    },
    {
      id: 'prod-22',
      title: 'Round Motif Jacket',
      slug: 'round-motif-jacket',
      description: "An elegantly structured jacket featuring round artistic motifs from Mona Niko's signature style. Premium fabric with artisanal finishing.",
      images: JSON.stringify(['/images/artworks/artwork-5.jpg']),
      type: 'DESIGNERS_COLLECTION',
      basePrice: 190,
      featured: false,
      tags: JSON.stringify(['jacket', 'designers-collection', 'motif', 'clothing']),
      variants: [
        { id: 'var-60', name: 'S', price: 190, stock: 3 },
        { id: 'var-61', name: 'M', price: 190, stock: 4 },
        { id: 'var-62', name: 'L', price: 190, stock: 3 },
      ],
    },
    {
      id: 'prod-23',
      title: 'Taffeta Collar Long Vest',
      slug: 'taffeta-collar-long-vest',
      description: "A sophisticated long vest with a dramatic taffeta collar. Part of Mona Niko's Designers Collection, blending high fashion with artistic sensibility.",
      images: JSON.stringify(['/images/artworks/artwork-6.jpg']),
      type: 'DESIGNERS_COLLECTION',
      basePrice: 192,
      featured: false,
      tags: JSON.stringify(['vest', 'designers-collection', 'taffeta', 'clothing']),
      variants: [
        { id: 'var-63', name: 'S', price: 192, stock: 2 },
        { id: 'var-64', name: 'M', price: 192, stock: 3 },
        { id: 'var-65', name: 'L', price: 192, stock: 2 },
      ],
    },
    {
      id: 'prod-24',
      title: 'Purple Blouse',
      slug: 'purple-blouse',
      description: "A luxurious purple blouse with artistic detailing from the Designers Collection. Flattering silhouette with unique design elements inspired by Mona Niko's paintings.",
      images: JSON.stringify(['/images/artworks/artwork-7.jpg']),
      type: 'DESIGNERS_COLLECTION',
      basePrice: 140,
      featured: true,
      tags: JSON.stringify(['blouse', 'designers-collection', 'purple', 'clothing']),
      variants: [
        { id: 'var-66', name: 'S', price: 140, stock: 4 },
        { id: 'var-67', name: 'M', price: 140, stock: 5 },
        { id: 'var-68', name: 'L', price: 140, stock: 3 },
      ],
    },
    {
      id: 'prod-25',
      title: 'Green Blouse',
      slug: 'green-blouse',
      description: 'A fresh and elegant green blouse from the Designers Collection. Art-inspired details and premium fabric create a piece that transitions from day to evening.',
      images: JSON.stringify(['/images/artworks/artwork-5.jpg']),
      type: 'DESIGNERS_COLLECTION',
      basePrice: 140,
      featured: false,
      tags: JSON.stringify(['blouse', 'designers-collection', 'green', 'clothing']),
      variants: [
        { id: 'var-69', name: 'S', price: 140, stock: 4 },
        { id: 'var-70', name: 'M', price: 140, stock: 5 },
        { id: 'var-71', name: 'L', price: 140, stock: 3 },
      ],
    },
    {
      id: 'prod-26',
      title: 'Printed Blouse',
      slug: 'printed-blouse',
      description: "A statement printed blouse featuring patterns derived from Mona Niko's artwork. Premium digital printing on luxurious fabric for a wearable masterpiece.",
      images: JSON.stringify(['/images/artworks/artwork-8.jpg']),
      type: 'DESIGNERS_COLLECTION',
      basePrice: 135,
      featured: false,
      tags: JSON.stringify(['blouse', 'designers-collection', 'printed', 'clothing']),
      variants: [
        { id: 'var-72', name: 'S', price: 135, stock: 5 },
        { id: 'var-73', name: 'M', price: 135, stock: 6 },
        { id: 'var-74', name: 'L', price: 135, stock: 4 },
      ],
    },
    {
      id: 'prod-27',
      title: 'Frilly Front Dress Navy Blue',
      slug: 'frilly-front-dress-navy-blue',
      description: 'An elegant navy blue dress with a distinctive frilly front detail from the Designers Collection. Perfect for gallery openings and special occasions.',
      images: JSON.stringify(['/images/artworks/artwork-6.jpg']),
      type: 'DESIGNERS_COLLECTION',
      basePrice: 198,
      featured: true,
      tags: JSON.stringify(['dress', 'designers-collection', 'navy', 'clothing']),
      variants: [
        { id: 'var-75', name: 'S', price: 198, stock: 2 },
        { id: 'var-76', name: 'M', price: 198, stock: 3 },
        { id: 'var-77', name: 'L', price: 198, stock: 2 },
      ],
    },
    {
      id: 'prod-28',
      title: 'High Collar Gathered Blouse White',
      slug: 'high-collar-gathered-blouse-white',
      description: 'A sophisticated white blouse with an architectural high collar and gathered detailing. Timeless elegance from the Designers Collection.',
      images: JSON.stringify(['/images/artworks/artwork-1.jpg']),
      type: 'DESIGNERS_COLLECTION',
      basePrice: 110,
      featured: false,
      tags: JSON.stringify(['blouse', 'designers-collection', 'white', 'clothing']),
      variants: [
        { id: 'var-78', name: 'S', price: 110, stock: 5 },
        { id: 'var-79', name: 'M', price: 110, stock: 6 },
        { id: 'var-80', name: 'L', price: 110, stock: 4 },
      ],
    },
  ];

  for (const prod of productsData) {
    const { variants, ...productData } = prod;
    await prisma.product.create({
      data: {
        ...productData,
        variants: {
          create: variants.map((v) => ({
            id: v.id,
            name: v.name,
            price: v.price,
            dimensions: (v as any).dimensions || null,
            stock: v.stock,
          })),
        },
      },
    });
  }
  console.log(`  Created ${productsData.length} products with variants.`);

  // ─── Workshops ─────────────────────────────────────────────
  console.log('Seeding workshops...');
  const workshopsData = [
    {
      id: 'ws-1',
      title: 'Mix Media & Acrylic for Adults',
      slug: 'mix-media-acrylic-adults',
      description: 'Learn mixed media and acrylic painting techniques in this monthly adult workshop led by Mona Niko.',
      longDescription: 'Join Mona Niko for an immersive monthly workshop exploring mixed media and acrylic techniques. Learn layering, texture building, color mixing, and composition in a supportive, creative environment. Each session focuses on different techniques and themes, building your skills over time. All materials included.',
      images: JSON.stringify(['/images/artworks/artwork-1.jpg']),
      date: new Date('2026-04-05'),
      endDate: new Date('2026-04-26'),
      time: '10:00 AM - 1:00 PM',
      duration: '3 hours per session (4 sessions/month)',
      location: 'Mona Niko Gallery, 668B The Shops At Mission Viejo Mall, Mission Viejo, CA 92691',
      isOnline: false,
      price: 150,
      capacity: 12,
      spotsLeft: 4,
      instructor: 'Mona Niko',
      level: 'ALL_LEVELS',
      materials: JSON.stringify(['Canvas', 'Acrylic paints', 'Mixed media supplies', 'Brushes', 'Palette knives']),
      featured: true,
    },
    {
      id: 'ws-2',
      title: 'Sculpting Workshop with Reza',
      slug: 'sculpting-workshop-reza',
      description: 'Discover the art of sculpting in this hands-on workshop led by master sculptor Reza.',
      longDescription: 'Learn fundamental sculpting techniques from master sculptor Reza in this engaging hands-on workshop. Explore form, proportion, and texture using professional-grade clay and tools. All materials provided.',
      images: JSON.stringify(['/images/artworks/artwork-5.jpg']),
      date: new Date('2026-04-12'),
      time: '2:00 PM - 5:00 PM',
      duration: '3 hours',
      location: 'Mona Niko Gallery, 668B The Shops At Mission Viejo Mall, Mission Viejo, CA 92691',
      isOnline: false,
      price: 85,
      capacity: 10,
      spotsLeft: 6,
      instructor: 'Reza',
      level: 'ALL_LEVELS',
      materials: JSON.stringify(['Sculpting clay', 'Tools', 'Armature wire']),
      featured: true,
    },
    {
      id: 'ws-3',
      title: 'Ceramic Clay Jewelry Workshop',
      slug: 'ceramic-clay-jewelry-workshop',
      description: 'Create beautiful handmade jewelry from ceramic clay in this creative workshop.',
      longDescription: 'Design and create your own unique ceramic clay jewelry pieces in this fun, creative workshop. Learn techniques for shaping, texturing, and finishing clay into stunning earrings, pendants, and bracelets. All materials and firing are included.',
      images: JSON.stringify(['/images/artworks/artwork-3.jpg']),
      date: new Date('2026-04-19'),
      time: '11:00 AM - 2:00 PM',
      duration: '3 hours',
      location: 'Mona Niko Gallery, 668B The Shops At Mission Viejo Mall, Mission Viejo, CA 92691',
      isOnline: false,
      price: 79,
      capacity: 10,
      spotsLeft: 5,
      instructor: 'Mona Niko',
      level: 'BEGINNER',
      materials: JSON.stringify(['Ceramic clay', 'Jewelry findings', 'Glazes', 'Tools']),
      featured: true,
    },
    {
      id: 'ws-4',
      title: 'Art & Paint Classes by Foujan',
      slug: 'art-paint-classes-foujan',
      description: 'Monthly art and painting classes taught by talented artist Foujan.',
      longDescription: 'Join artist Foujan for monthly painting classes designed to develop your artistic skills and creative expression. Each class explores different painting techniques, from color theory to composition, with personalized guidance. Materials included.',
      images: JSON.stringify(['/images/artworks/artwork-4.jpg']),
      date: new Date('2026-04-07'),
      endDate: new Date('2026-04-28'),
      time: '6:00 PM - 8:00 PM',
      duration: '2 hours per session (4 sessions/month)',
      location: 'Mona Niko Gallery, 668B The Shops At Mission Viejo Mall, Mission Viejo, CA 92691',
      isOnline: false,
      price: 150,
      capacity: 15,
      spotsLeft: 7,
      instructor: 'Foujan',
      level: 'ALL_LEVELS',
      materials: JSON.stringify(['Canvas', 'Acrylic paints', 'Brushes']),
      featured: false,
    },
    {
      id: 'ws-5',
      title: 'Kids Club',
      slug: 'kids-club',
      description: 'Fun and creative art sessions designed especially for children. Single session or monthly membership available.',
      longDescription: 'A fun, nurturing environment where kids can explore their creativity through painting, drawing, and mixed media projects. Each session introduces new techniques and themes appropriate for young artists. Ages 5-12.',
      images: JSON.stringify(['/images/artworks/artwork-7.jpg']),
      date: new Date('2026-04-05'),
      endDate: new Date('2026-04-26'),
      time: '3:30 PM - 5:00 PM',
      duration: '1.5 hours per session',
      location: 'Mona Niko Gallery, 668B The Shops At Mission Viejo Mall, Mission Viejo, CA 92691',
      isOnline: false,
      price: 35,
      capacity: 12,
      spotsLeft: 5,
      instructor: 'Mona Niko',
      level: 'BEGINNER',
      materials: JSON.stringify(['Art supplies', 'Paper', 'Paint', 'Brushes']),
      featured: true,
    },
    {
      id: 'ws-6',
      title: 'Wine and Painting Night',
      slug: 'wine-and-painting-night',
      description: 'Sip, paint, and socialize in this relaxing evening of creativity and wine.',
      longDescription: 'Unwind and unleash your creativity at our popular Wine and Painting Night. Enjoy complimentary wine and light refreshments while Mona Niko guides you step-by-step through creating your own beautiful painting. No experience necessary.',
      images: JSON.stringify(['/images/artworks/artwork-2.jpg']),
      date: new Date('2026-04-18'),
      time: '7:00 PM - 9:30 PM',
      duration: '2.5 hours',
      location: 'Mona Niko Gallery, 668B The Shops At Mission Viejo Mall, Mission Viejo, CA 92691',
      isOnline: false,
      price: 65,
      capacity: 20,
      spotsLeft: 8,
      instructor: 'Mona Niko',
      level: 'BEGINNER',
      materials: JSON.stringify(['Canvas', 'Acrylic paints', 'Brushes', 'Wine & refreshments']),
      featured: true,
    },
    {
      id: 'ws-7',
      title: 'Candle Design Class by Eliane Cherman',
      slug: 'candle-design-class-eliane-cherman',
      description: 'Learn the art of candle making and design with expert artisan Eliane Cherman.',
      longDescription: 'Create beautiful, custom-designed candles under the expert guidance of artisan Eliane Cherman. Learn about different wax types, scent blending, wick selection, and decorative techniques. All materials provided.',
      images: JSON.stringify(['/images/artworks/artwork-8.jpg']),
      date: new Date('2026-04-26'),
      time: '11:00 AM - 1:30 PM',
      duration: '2.5 hours',
      location: 'Mona Niko Gallery, 668B The Shops At Mission Viejo Mall, Mission Viejo, CA 92691',
      isOnline: false,
      price: 75,
      capacity: 12,
      spotsLeft: 9,
      instructor: 'Eliane Cherman',
      level: 'BEGINNER',
      materials: JSON.stringify(['Soy wax', 'Fragrance oils', 'Wicks', 'Containers', 'Decorative elements']),
      featured: false,
    },
    {
      id: 'ws-8',
      title: 'Kids & Mom Art Workshop',
      slug: 'kids-and-mom-art-workshop',
      description: 'A special bonding experience for mothers and children to create art together.',
      longDescription: 'Share a special creative experience with your child in this unique art workshop designed for mothers (or caregivers) and kids to create together. Work on collaborative and individual art projects. All materials included. Suitable for ages 4 and up.',
      images: JSON.stringify(['/images/artworks/artwork-6.jpg']),
      date: new Date('2026-04-13'),
      time: '10:00 AM - 12:00 PM',
      duration: '2 hours',
      location: 'Mona Niko Gallery, 668B The Shops At Mission Viejo Mall, Mission Viejo, CA 92691',
      isOnline: false,
      price: 39,
      capacity: 16,
      spotsLeft: 6,
      instructor: 'Mona Niko',
      level: 'BEGINNER',
      materials: JSON.stringify(['Art supplies', 'Canvas', 'Paint']),
      featured: false,
    },
    {
      id: 'ws-9',
      title: "Celebrate Your Child's Birthday",
      slug: 'celebrate-your-childs-birthday',
      description: 'Host a unique and creative birthday party at the gallery with art activities for kids.',
      longDescription: "Make your child's birthday unforgettable with a creative art party at Mona Niko Gallery. Kids will enjoy guided art activities, painting projects, and creative games. Available for ages 4-14.",
      images: JSON.stringify(['/images/artworks/artwork-7.jpg']),
      date: new Date('2026-04-20'),
      time: 'By Appointment',
      duration: '2-3 hours (customizable)',
      location: 'Mona Niko Gallery, 668B The Shops At Mission Viejo Mall, Mission Viejo, CA 92691',
      isOnline: false,
      price: 250,
      capacity: 20,
      spotsLeft: 20,
      instructor: 'Mona Niko',
      level: 'BEGINNER',
      materials: JSON.stringify(['Art supplies', 'Canvas', 'Party supplies']),
      featured: false,
    },
    {
      id: 'ws-10',
      title: 'Mix Media & Acrylic Online Painting Class',
      slug: 'mix-media-acrylic-online-class',
      description: 'Learn mixed media and acrylic techniques from the comfort of your home with Mona Niko.',
      longDescription: 'Cannot make it to the gallery? Join Mona Niko online for this interactive mixed media and acrylic painting class. Learn layering, texture, and color techniques via live Zoom session. Materials list provided in advance. Recorded for 30-day replay access.',
      images: JSON.stringify(['/images/artworks/artwork-1.jpg']),
      date: new Date('2026-04-15'),
      time: '11:00 AM - 2:00 PM PST',
      duration: '3 hours',
      location: 'Online via Zoom',
      isOnline: true,
      price: 95,
      capacity: 30,
      spotsLeft: 18,
      instructor: 'Mona Niko',
      level: 'ALL_LEVELS',
      materials: JSON.stringify(['Canvas', 'Acrylic paints', 'Mixed media supplies', 'Brushes']),
      featured: false,
    },
  ];

  for (const ws of workshopsData) {
    await prisma.workshop.create({ data: ws });
  }
  console.log(`  Created ${workshopsData.length} workshops.`);

  // ─── Journal Posts ─────────────────────────────────────────
  console.log('Seeding journal posts...');
  const journalPostsData = [
    {
      id: 'jp-1',
      title: "The Story Behind 'Portraits of Strength'",
      slug: 'story-behind-portraits-of-strength',
      excerpt: 'An intimate look at the inspiration and process behind my most personal collection — celebrating the resilience and beauty of women everywhere.',
      content: 'Every portrait in this collection began with a story. Some were stories I witnessed firsthand, others were whispered to me across cultures and continents. The Portraits of Strength collection represents years of observation, empathy, and artistic exploration into what makes women extraordinary.',
      coverImage: '/images/artworks/artwork-1.jpg',
      author: 'Mona Niko',
      category: 'Studio Diary',
      tags: JSON.stringify(['collection', 'portraits', 'women', 'inspiration']),
      status: 'PUBLISHED',
      publishedAt: new Date('2024-08-15'),
      seoTitle: "The Story Behind Portraits of Strength | Mona Niko Gallery",
      seoDescription: "Discover the inspiration behind Mona Niko's Portraits of Strength collection at Mission Viejo",
    },
    {
      id: 'jp-2',
      title: 'Persian Heritage in Contemporary Art',
      slug: 'persian-heritage-contemporary-art',
      excerpt: 'How the rich artistic traditions of Iran — from Qajar portraiture to Eslimi patterns — continue to inspire my work and connect past to present.',
      content: 'Growing up immersed in Persian art and culture gave me a visual vocabulary that I carry into every piece I create. The intricate geometries of Eslimi, the regal presence of Qajar portraiture, and the poetic symbolism woven through centuries of Iranian art — these elements live in my brushstrokes.',
      coverImage: '/images/artworks/artwork-5.jpg',
      author: 'Mona Niko',
      category: 'Reflections',
      tags: JSON.stringify(['persian', 'heritage', 'qajar', 'culture', 'identity']),
      status: 'PUBLISHED',
      publishedAt: new Date('2024-07-20'),
      seoTitle: 'Persian Heritage in Contemporary Art | Mona Niko Gallery',
      seoDescription: 'Exploring how Persian artistic traditions shape contemporary expression at Mona Niko Gallery',
    },
    {
      id: 'jp-3',
      title: "Collector's Guide: Living with Original Art",
      slug: 'collectors-guide-living-with-art',
      excerpt: 'Practical advice for new collectors on displaying, caring for, and building a meaningful art collection that grows with you.',
      content: 'Building an art collection is one of the most rewarding journeys you can undertake. It is deeply personal, endlessly surprising, and profoundly enriching. Whether you are acquiring your first original piece or adding to an established collection, here are my thoughts on living with art.',
      coverImage: '/images/artworks/artwork-2.jpg',
      author: 'Mona Niko',
      category: "Collector's Corner",
      tags: JSON.stringify(['collecting', 'guide', 'tips', 'art-care']),
      status: 'PUBLISHED',
      publishedAt: new Date('2024-06-10'),
      seoTitle: "Collector's Guide to Living with Original Art | Mona Niko Gallery",
      seoDescription: 'Expert advice on building and caring for your art collection from Mona Niko Gallery',
    },
    {
      id: 'jp-4',
      title: 'Inside the Workshop: Mixed Media Techniques',
      slug: 'inside-workshop-mixed-media-techniques',
      excerpt: 'A behind-the-scenes look at our most popular workshop — mixed media and acrylic painting — and what makes it such a transformative experience for students.',
      content: 'Our mixed media workshop is more than just a painting class. It is a space where creativity flows freely, where beginners discover hidden talents, and where experienced artists push their boundaries. In this post I share some of the techniques we explore and the magic that happens when people create together.',
      coverImage: '/images/artworks/artwork-8.jpg',
      author: 'Mona Niko',
      category: 'Workshops',
      tags: JSON.stringify(['workshop', 'mixed-media', 'technique', 'education']),
      status: 'DRAFT',
      seoTitle: 'Inside the Workshop: Mixed Media Techniques | Mona Niko Gallery',
      seoDescription: 'Explore mixed media painting techniques at Mona Niko Gallery workshops in Mission Viejo',
    },
    {
      id: 'jp-5',
      title: 'The Designers Collection: Where Art Meets Fashion',
      slug: 'designers-collection-art-meets-fashion',
      excerpt: 'How I bring my artistic vision to wearable art — the creative process behind transforming paintings into jackets, dresses, and blouses.',
      content: 'Fashion and art have always been intertwined in my world. When I launched the Designers Collection, my goal was to create pieces that carry the same emotional weight and visual impact as my paintings but in a form you can wear and share with the world.',
      coverImage: '/images/artworks/artwork-4.jpg',
      author: 'Mona Niko',
      category: 'Studio Diary',
      tags: JSON.stringify(['fashion', 'designers-collection', 'wearable-art', 'process']),
      status: 'SCHEDULED',
      scheduledAt: new Date('2026-03-25T09:00:00Z'),
      seoTitle: 'Designers Collection: Art Meets Fashion | Mona Niko Gallery',
      seoDescription: "Discover the creative process behind Mona Niko's wearable art Designers Collection",
    },
  ];

  for (const jp of journalPostsData) {
    await prisma.journalPost.create({ data: jp });
  }
  console.log(`  Created ${journalPostsData.length} journal posts.`);

  // ─── Testimonials ──────────────────────────────────────────
  console.log('Seeding testimonials...');
  const testimonialsData = [
    {
      id: 'test-1',
      name: 'Sarah M.',
      role: 'Art Collector, Newport Beach',
      text: "Mona's work has transformed our home. The painting we acquired from the gallery has become the centerpiece of our living room and a conversation starter at every gathering. Her understanding of color and emotion is extraordinary.",
      featured: true,
      rating: 5,
    },
    {
      id: 'test-2',
      name: 'David C.',
      role: 'Interior Designer, Laguna Beach',
      text: 'I have commissioned several custom paintings from Mona for my clients. Her ability to create pieces that perfectly complement a space while maintaining her artistic voice is rare and invaluable. My clients are always thrilled.',
      featured: true,
      rating: 5,
    },
    {
      id: 'test-3',
      name: 'Alexandra R.',
      role: 'Workshop Attendee, Mission Viejo',
      text: 'The mixed media workshop was life-changing. Mona creates such an inspiring, supportive environment. I left with not just a painting, but a new perspective on creativity. I have been coming back every month since.',
      featured: true,
      rating: 5,
    },
    {
      id: 'test-4',
      name: 'Jennifer L.',
      role: 'Parent, Irvine',
      text: 'My daughter absolutely loves the Kids Club at Mona Niko Gallery. She comes home every week excited to show us what she created. The instructors are patient, creative, and wonderful with children. Worth every penny.',
      featured: true,
      rating: 5,
    },
    {
      id: 'test-5',
      name: 'Michael T.',
      role: 'Collector, Dana Point',
      text: "The quality of Mona's original paintings is museum-grade. I purchased 'Golden Girl' and 'Freedom' and both pieces have that rare quality of revealing something new every time you look at them. A true investment in beauty.",
      featured: false,
      rating: 5,
    },
    {
      id: 'test-6',
      name: 'Parisa K.',
      role: 'Workshop Attendee, Lake Forest',
      text: "As a Persian woman, Mona's art speaks to my soul. Her ability to blend traditional Persian motifs with contemporary expression is beautiful. The sculpting workshop with Reza was also incredible — I had never tried sculpting before and he made it so approachable.",
      featured: true,
      rating: 5,
    },
  ];

  for (const t of testimonialsData) {
    await prisma.testimonial.create({ data: t });
  }
  console.log(`  Created ${testimonialsData.length} testimonials.`);

  // ─── Press Items ───────────────────────────────────────────
  console.log('Seeding press items...');
  const pressItemsData = [
    {
      id: 'press-1',
      title: 'Mona Niko Brings Art and Community to Mission Viejo',
      publication: 'OC Register',
      date: new Date('2024-06-15'),
      excerpt: 'Iranian-American artist Mona Niko has transformed a space at The Shops at Mission Viejo into a vibrant gallery and creative hub, offering original paintings, workshops, and a unique designers collection.',
      featured: true,
    },
    {
      id: 'press-2',
      title: 'The Rise of Mall Gallery Spaces in Orange County',
      publication: 'Modern Luxury Orange County',
      date: new Date('2024-04-22'),
      excerpt: 'Mona Niko Gallery is leading a new wave of accessible art spaces, proving that fine art can thrive in unexpected locations like shopping malls, bringing creativity to everyday spaces.',
      featured: true,
    },
    {
      id: 'press-3',
      title: 'Art Workshops That Are Changing Lives in South OC',
      publication: 'Laguna Beach Magazine',
      date: new Date('2024-09-10'),
      excerpt: 'From sculpting with Reza to mixed media with Mona herself, the workshops at Mona Niko Gallery have become a sought-after experience for both aspiring artists and wellness seekers in Orange County.',
      featured: true,
    },
    {
      id: 'press-4',
      title: 'Persian Heritage in Contemporary California Art',
      publication: 'Kayhan Life',
      date: new Date('2024-11-05'),
      excerpt: 'Mona Niko\'s work masterfully bridges the gap between traditional Persian artistic traditions and contemporary Western expression, creating a visual dialogue that resonates across cultures.',
      featured: false,
    },
    {
      id: 'press-5',
      title: 'Wearable Art: Where Fashion Meets the Canvas',
      publication: 'Riviera Orange County',
      date: new Date('2025-01-20'),
      excerpt: 'The Designers Collection at Mona Niko Gallery offers a unique proposition — clothing that doubles as art. From hand-embellished jackets to printed blouses, each piece carries the artist\'s signature aesthetic.',
      featured: false,
    },
  ];

  for (const p of pressItemsData) {
    await prisma.pressItem.create({ data: p });
  }
  console.log(`  Created ${pressItemsData.length} press items.`);

  // ─── Inquiries ─────────────────────────────────────────────
  console.log('Seeding inquiries...');
  const inquiriesData = [
    {
      id: 'inq-1',
      type: 'ARTWORK',
      name: 'Sarah Mitchell',
      email: 'sarah.mitchell@example.com',
      phone: '(949) 555-0101',
      message: "I'm very interested in 'Layers of the Soul'. Could you provide more details about the piece and arrange a private viewing?",
      artworkId: 'art-1',
      status: 'CONTACTED',
      createdAt: new Date('2026-02-15'),
    },
    {
      id: 'inq-2',
      type: 'COMMISSION',
      name: 'David Chen',
      email: 'david.chen@example.com',
      phone: '(949) 555-0102',
      message: "I'm an interior designer working on a luxury residential project in Newport Beach. I'd like to discuss commissioning a large-scale piece (approx 6ft x 4ft) for my client's living room. Budget is flexible.",
      budget: '$15,000 - $25,000',
      status: 'IN_PROGRESS',
      createdAt: new Date('2026-02-20'),
    },
    {
      id: 'inq-3',
      type: 'PRIVATE_VIEWING',
      name: 'James Thornton',
      email: 'james.thornton@example.com',
      phone: '(949) 555-0103',
      message: 'I would love to arrange a private viewing of the latest collection. Is the studio available for a visit next weekend?',
      status: 'CONTACTED',
      createdAt: new Date('2026-02-25'),
    },
    {
      id: 'inq-4',
      type: 'GENERAL',
      name: 'Emily Watts',
      email: 'emily.watts@example.com',
      message: 'Do you offer gift cards for the gallery shop? I would love to give one as a birthday gift.',
      status: 'CLOSED',
      createdAt: new Date('2026-01-10'),
    },
    {
      id: 'inq-5',
      type: 'PRESS',
      name: 'Michael Ross',
      email: 'michael.ross@artforum.com',
      message: "I'm writing a feature on contemporary Iranian-American artists for ArtForum. I'd love to interview Mona Niko about her practice and the gallery. Could we schedule a conversation?",
      status: 'NEW',
      createdAt: new Date('2026-03-01'),
    },
    {
      id: 'inq-6',
      type: 'ARTWORK',
      name: 'Robert Garcia',
      email: 'robert.garcia@example.com',
      phone: '(949) 555-0106',
      message: "I'm interested in purchasing 'Three Women' for our corporate office. Can you provide pricing and delivery details?",
      artworkId: 'art-8',
      status: 'NEW',
      createdAt: new Date('2026-03-05'),
    },
    {
      id: 'inq-7',
      type: 'COMMISSION',
      name: 'Patricia Lane',
      email: 'patricia.lane@modernluxury.com',
      message: "I'd like to commission a portrait in Mona's signature style as a gift for my husband. Could we discuss options and timeline?",
      budget: '$5,000 - $10,000',
      status: 'NEW',
      createdAt: new Date('2026-03-07'),
    },
    {
      id: 'inq-8',
      type: 'GENERAL',
      name: 'Lisa Nakamura',
      email: 'lisa.nakamura@example.com',
      message: 'I attended a workshop last month and absolutely loved it. Do you have a schedule for upcoming workshops? Also interested in the Kids Club for my daughter.',
      status: 'CONTACTED',
      createdAt: new Date('2026-03-02'),
    },
  ];

  for (const inq of inquiriesData) {
    await prisma.inquiry.create({ data: inq });
  }
  console.log(`  Created ${inquiriesData.length} inquiries.`);

  // ─── Subscribers ───────────────────────────────────────────
  console.log('Seeding subscribers...');
  const subscribersData = [
    {
      id: 'sub-1',
      email: 'sarah.mitchell@example.com',
      firstName: 'Sarah',
      lastName: 'Mitchell',
      segments: JSON.stringify(['collector', 'vip']),
      source: 'Gallery Visit',
      isActive: true,
    },
    {
      id: 'sub-2',
      email: 'david.chen@example.com',
      firstName: 'David',
      lastName: 'Chen',
      segments: JSON.stringify(['commission_lead', 'collector']),
      source: 'Referral',
      isActive: true,
    },
    {
      id: 'sub-3',
      email: 'alexandra.rivera@example.com',
      firstName: 'Alexandra',
      lastName: 'Rivera',
      segments: JSON.stringify(['workshop_attendee', 'newsletter']),
      source: 'Workshop Registration',
      isActive: true,
    },
    {
      id: 'sub-4',
      email: 'james.thornton@example.com',
      firstName: 'James',
      lastName: 'Thornton',
      segments: JSON.stringify(['collector', 'vip']),
      source: 'Art Fair',
      isActive: true,
    },
    {
      id: 'sub-5',
      email: 'emily.watts@example.com',
      firstName: 'Emily',
      lastName: 'Watts',
      segments: JSON.stringify(['print_buyer', 'newsletter']),
      source: 'Online Shop',
      isActive: true,
    },
    {
      id: 'sub-6',
      email: 'michael.ross@artforum.com',
      firstName: 'Michael',
      lastName: 'Ross',
      segments: JSON.stringify(['press']),
      source: 'Press Inquiry',
      isActive: true,
    },
    {
      id: 'sub-7',
      email: 'lisa.nakamura@example.com',
      firstName: 'Lisa',
      lastName: 'Nakamura',
      segments: JSON.stringify(['workshop_attendee', 'print_buyer']),
      source: 'Instagram',
      isActive: true,
    },
    {
      id: 'sub-8',
      email: 'robert.garcia@example.com',
      firstName: 'Robert',
      lastName: 'Garcia',
      segments: JSON.stringify(['collector', 'commission_lead', 'vip']),
      source: 'Gallery Visit',
      isActive: true,
    },
    {
      id: 'sub-9',
      email: 'anna.kowalski@example.com',
      firstName: 'Anna',
      lastName: 'Kowalski',
      segments: JSON.stringify(['newsletter']),
      source: 'Website Signup',
      isActive: true,
    },
    {
      id: 'sub-10',
      email: 'patricia.lane@modernluxury.com',
      firstName: 'Patricia',
      lastName: 'Lane',
      segments: JSON.stringify(['press', 'newsletter']),
      source: 'Press Event',
      isActive: true,
    },
    {
      id: 'sub-11',
      email: 'jennifer.liu@example.com',
      firstName: 'Jennifer',
      lastName: 'Liu',
      segments: JSON.stringify(['newsletter', 'workshop_attendee']),
      source: 'Website Signup',
      isActive: true,
    },
    {
      id: 'sub-12',
      email: 'mark.henderson@example.com',
      firstName: 'Mark',
      lastName: 'Henderson',
      segments: JSON.stringify(['collector']),
      source: 'Art Fair',
      isActive: true,
    },
    {
      id: 'sub-13',
      email: 'sophia.martini@example.com',
      firstName: 'Sophia',
      lastName: 'Martini',
      segments: JSON.stringify(['print_buyer', 'newsletter']),
      source: 'Online Shop',
      isActive: false,
    },
    {
      id: 'sub-14',
      email: 'kevin.park@example.com',
      firstName: 'Kevin',
      lastName: 'Park',
      segments: JSON.stringify(['newsletter']),
      source: 'Website Signup',
      isActive: true,
    },
    {
      id: 'sub-15',
      email: 'rachel.adams@example.com',
      firstName: 'Rachel',
      lastName: 'Adams',
      segments: JSON.stringify(['workshop_attendee', 'newsletter', 'print_buyer']),
      source: 'Workshop Registration',
      isActive: true,
    },
  ];

  for (const sub of subscribersData) {
    await prisma.subscriber.create({ data: sub });
  }
  console.log(`  Created ${subscribersData.length} subscribers.`);

  // ─── Orders ────────────────────────────────────────────────
  console.log('Seeding orders...');
  const ordersData = [
    {
      id: 'ord-1',
      orderNumber: 'ORD-1001',
      userId: 'user-admin-1',
      customerEmail: 'sarah.mitchell@example.com',
      customerName: 'Sarah Mitchell',
      customerPhone: '(949) 555-0101',
      shippingAddress: JSON.stringify({ line1: '1234 Ocean Blvd', city: 'Newport Beach', state: 'CA', zip: '92660', country: 'US' }),
      subtotal: 8500,
      tax: 722.50,
      shipping: 0,
      total: 9222.50,
      status: 'DELIVERED',
      paymentStatus: 'PAID',
      notes: 'VIP collector - white glove delivery',
      createdAt: new Date('2025-11-15'),
      items: [
        { id: 'oi-1', title: 'Layers of the Soul — Original', image: '/images/artworks/artwork-1.jpg', price: 8500, quantity: 1 },
      ],
    },
    {
      id: 'ord-2',
      orderNumber: 'ORD-1002',
      customerEmail: 'emily.watts@example.com',
      customerName: 'Emily Watts',
      customerPhone: '(949) 555-0105',
      shippingAddress: JSON.stringify({ line1: '567 Maple Ave', city: 'Irvine', state: 'CA', zip: '92614', country: 'US' }),
      subtotal: 450,
      tax: 38.25,
      shipping: 12,
      total: 500.25,
      status: 'DELIVERED',
      paymentStatus: 'PAID',
      createdAt: new Date('2025-12-02'),
      items: [
        { id: 'oi-2', title: 'Layers of the Soul — Limited Edition Print 24" x 24"', image: '/images/artworks/artwork-1.jpg', price: 450, quantity: 1 },
      ],
    },
    {
      id: 'ord-3',
      orderNumber: 'ORD-1003',
      customerEmail: 'lisa.nakamura@example.com',
      customerName: 'Lisa Nakamura',
      shippingAddress: JSON.stringify({ line1: '890 Elm St', city: 'Lake Forest', state: 'CA', zip: '92630', country: 'US' }),
      subtotal: 145,
      tax: 12.33,
      shipping: 8,
      total: 165.33,
      status: 'DELIVERED',
      paymentStatus: 'PAID',
      createdAt: new Date('2025-12-20'),
      items: [
        { id: 'oi-3', title: 'Freedom Phone Case - iPhone 14/15', image: '/images/artworks/artwork-3.jpg', price: 35, quantity: 1 },
        { id: 'oi-4', title: 'High Collar Gathered Blouse White - M', image: '/images/artworks/artwork-1.jpg', price: 110, quantity: 1 },
      ],
    },
    {
      id: 'ord-4',
      orderNumber: 'ORD-1004',
      customerEmail: 'james.thornton@example.com',
      customerName: 'James Thornton',
      customerPhone: '(949) 555-0103',
      shippingAddress: JSON.stringify({ line1: '2100 Pacific Coast Hwy', city: 'Laguna Beach', state: 'CA', zip: '92651', country: 'US' }),
      subtotal: 14500,
      tax: 1232.50,
      shipping: 0,
      total: 15732.50,
      status: 'DELIVERED',
      paymentStatus: 'PAID',
      notes: 'Repeat collector - second major purchase',
      createdAt: new Date('2026-01-10'),
      items: [
        { id: 'oi-5', title: 'Three Women — Original', image: '/images/artworks/artwork-8.jpg', price: 14500, quantity: 1 },
      ],
    },
    {
      id: 'ord-5',
      orderNumber: 'ORD-1005',
      customerEmail: 'jennifer.liu@example.com',
      customerName: 'Jennifer Liu',
      shippingAddress: JSON.stringify({ line1: '345 University Dr', city: 'Irvine', state: 'CA', zip: '92612', country: 'US' }),
      subtotal: 350,
      tax: 29.75,
      shipping: 10,
      total: 389.75,
      status: 'SHIPPED',
      paymentStatus: 'PAID',
      createdAt: new Date('2026-02-14'),
      items: [
        { id: 'oi-6', title: 'Freedom — Limited Edition Print 18" x 24"', image: '/images/artworks/artwork-3.jpg', price: 350, quantity: 1 },
      ],
    },
    {
      id: 'ord-6',
      orderNumber: 'ORD-1006',
      customerEmail: 'mark.henderson@example.com',
      customerName: 'Mark Henderson',
      customerPhone: '(949) 555-0112',
      shippingAddress: JSON.stringify({ line1: '789 Coast Dr', city: 'Dana Point', state: 'CA', zip: '92629', country: 'US' }),
      subtotal: 275,
      tax: 23.38,
      shipping: 10,
      total: 308.38,
      status: 'PROCESSING',
      paymentStatus: 'PAID',
      createdAt: new Date('2026-02-28'),
      items: [
        { id: 'oi-7', title: 'Tiny Colorful Jacket - M', image: '/images/artworks/artwork-4.jpg', price: 200, quantity: 1 },
        { id: 'oi-8', title: 'Love Silk Tie - Standard', image: '/images/artworks/artwork-4.jpg', price: 75, quantity: 1 },
      ],
    },
    {
      id: 'ord-7',
      orderNumber: 'ORD-1007',
      customerEmail: 'rachel.adams@example.com',
      customerName: 'Rachel Adams',
      shippingAddress: JSON.stringify({ line1: '456 Birch Ln', city: 'Mission Viejo', state: 'CA', zip: '92692', country: 'US' }),
      subtotal: 120,
      tax: 10.20,
      shipping: 8,
      total: 138.20,
      status: 'CONFIRMED',
      paymentStatus: 'PAID',
      createdAt: new Date('2026-03-01'),
      items: [
        { id: 'oi-9', title: 'Super Woman Art Cushion 18" x 18"', image: '/images/artworks/artwork-4.jpg', price: 55, quantity: 1 },
        { id: 'oi-10', title: 'Freedom Art Leggings - M', image: '/images/artworks/artwork-3.jpg', price: 65, quantity: 1 },
      ],
    },
    {
      id: 'ord-8',
      orderNumber: 'ORD-1008',
      customerEmail: 'kevin.park@example.com',
      customerName: 'Kevin Park',
      shippingAddress: JSON.stringify({ line1: '1010 Technology Dr', city: 'San Clemente', state: 'CA', zip: '92673', country: 'US' }),
      subtotal: 189,
      tax: 16.07,
      shipping: 15,
      total: 220.07,
      status: 'PENDING',
      paymentStatus: 'PENDING',
      createdAt: new Date('2026-03-05'),
      items: [
        { id: 'oi-11', title: 'Freedom Suitcase - Carry-On (20")', image: '/images/artworks/artwork-3.jpg', price: 189, quantity: 1 },
      ],
    },
    {
      id: 'ord-9',
      orderNumber: 'ORD-1009',
      customerEmail: 'sophia.martini@example.com',
      customerName: 'Sophia Martini',
      shippingAddress: JSON.stringify({ line1: '222 Vista Rd', city: 'Laguna Niguel', state: 'CA', zip: '92677', country: 'US' }),
      subtotal: 90,
      tax: 7.65,
      shipping: 8,
      total: 105.65,
      status: 'CANCELLED',
      paymentStatus: 'REFUNDED',
      notes: 'Customer requested cancellation before shipping',
      createdAt: new Date('2026-02-10'),
      items: [
        { id: 'oi-12', title: "Hands On Face Men's T-Shirt - L", image: '/images/artworks/artwork-2.jpg', price: 45, quantity: 2 },
      ],
    },
    {
      id: 'ord-10',
      orderNumber: 'ORD-1010',
      customerEmail: 'robert.garcia@example.com',
      customerName: 'Robert Garcia',
      customerPhone: '(949) 555-0108',
      shippingAddress: JSON.stringify({ line1: '5500 Corporate Plaza', city: 'Newport Beach', state: 'CA', zip: '92660', country: 'US' }),
      subtotal: 9800,
      tax: 833.00,
      shipping: 0,
      total: 10633.00,
      status: 'DELIVERED',
      paymentStatus: 'PAID',
      notes: 'Corporate purchase for office lobby',
      createdAt: new Date('2026-01-25'),
      items: [
        { id: 'oi-13', title: 'Golden Girl — Original', image: '/images/artworks/artwork-1.jpg', price: 9800, quantity: 1 },
      ],
    },
  ];

  for (const ord of ordersData) {
    const { items, ...orderData } = ord;
    await prisma.order.create({
      data: {
        ...orderData,
        items: {
          create: items.map((item) => ({
            id: item.id,
            title: item.title,
            image: item.image,
            price: item.price,
            quantity: item.quantity,
          })),
        },
      },
    });
  }
  console.log(`  Created ${ordersData.length} orders with items.`);

  // ─── Campaigns ─────────────────────────────────────────────
  console.log('Seeding campaigns...');
  const campaignsData = [
    {
      id: 'camp-1',
      title: 'Luminous Collection Launch',
      description: 'Multi-channel campaign to launch the new Luminous collection. Targeting collectors and high-value subscribers with exclusive previews and early access.',
      objective: 'LAUNCH',
      channels: JSON.stringify(['email', 'instagram', 'facebook']),
      status: 'COMPLETED',
      startDate: new Date('2025-09-01'),
      endDate: new Date('2025-09-30'),
      targetSegments: JSON.stringify(['collector', 'vip', 'newsletter']),
      metrics: JSON.stringify({ impressions: 45200, clicks: 3840, conversions: 18, inquiries: 12, revenue: 38500, openRate: 42.3, clickRate: 8.5 }),
    },
    {
      id: 'camp-2',
      title: 'Spring Workshop Series Promo',
      description: 'Promote spring workshop schedule to past attendees and interested subscribers. Focus on driving bookings.',
      objective: 'EVENT_BOOKING',
      channels: JSON.stringify(['email', 'instagram']),
      status: 'ACTIVE',
      startDate: new Date('2026-02-15'),
      endDate: new Date('2026-04-15'),
      targetSegments: JSON.stringify(['workshop_attendee', 'newsletter']),
      metrics: JSON.stringify({ impressions: 18400, clicks: 1560, conversions: 9, inquiries: 5, revenue: 2655, openRate: 38.7, clickRate: 7.2 }),
    },
    {
      id: 'camp-3',
      title: 'VIP Collector Private Viewing Invite',
      description: 'Exclusive email invitation to VIP collectors and top buyers for a private studio viewing of upcoming works.',
      objective: 'ENGAGEMENT',
      channels: JSON.stringify(['email']),
      status: 'SCHEDULED',
      startDate: new Date('2026-03-20'),
      endDate: new Date('2026-03-25'),
      targetSegments: JSON.stringify(['vip', 'collector']),
      metrics: JSON.stringify({ impressions: 0, clicks: 0, conversions: 0, inquiries: 0, revenue: 0 }),
    },
    {
      id: 'camp-4',
      title: 'Holiday Gift Guide — Prints & Originals',
      description: 'Seasonal campaign targeting print buyers and newsletter subscribers. Gift guide with curated selections at multiple price points.',
      objective: 'SALES',
      channels: JSON.stringify(['email', 'instagram', 'pinterest', 'facebook']),
      status: 'DRAFT',
      startDate: new Date('2026-11-15'),
      endDate: new Date('2026-12-24'),
      targetSegments: JSON.stringify(['print_buyer', 'newsletter', 'collector']),
      metrics: JSON.stringify({ impressions: 0, clicks: 0, conversions: 0, inquiries: 0, revenue: 0 }),
    },
    {
      id: 'camp-5',
      title: 'Unveiled Collection Awareness',
      description: 'Brand awareness campaign for the Unveiled figurative collection. Multi-platform push with behind-the-scenes content.',
      objective: 'AWARENESS',
      channels: JSON.stringify(['instagram', 'facebook', 'blog', 'x']),
      status: 'PAUSED',
      startDate: new Date('2025-11-01'),
      endDate: new Date('2025-12-15'),
      targetSegments: JSON.stringify(['newsletter', 'press']),
      metrics: JSON.stringify({ impressions: 32100, clicks: 2200, conversions: 4, inquiries: 8, revenue: 9800, clickRate: 6.9 }),
    },
  ];

  for (const camp of campaignsData) {
    await prisma.campaign.create({ data: camp });
  }
  console.log(`  Created ${campaignsData.length} campaigns.`);

  // ─── Promo Codes ───────────────────────────────────────────
  console.log('Seeding promo codes...');
  const promoCodesData = [
    {
      id: 'promo-1',
      code: 'WELCOME10',
      description: '10% off your first purchase',
      discountType: 'PERCENTAGE',
      discountValue: 10,
      minPurchase: 50,
      maxUses: 500,
      usedCount: 127,
      validFrom: new Date('2025-01-01'),
      validUntil: new Date('2026-12-31'),
      isActive: true,
    },
    {
      id: 'promo-2',
      code: 'VIP20',
      description: '20% off for VIP collectors',
      discountType: 'PERCENTAGE',
      discountValue: 20,
      minPurchase: 200,
      maxUses: 50,
      usedCount: 12,
      validFrom: new Date('2026-01-01'),
      validUntil: new Date('2026-06-30'),
      isActive: true,
    },
    {
      id: 'promo-3',
      code: 'FREESHIP',
      description: 'Free shipping on orders over $100',
      discountType: 'FIXED',
      discountValue: 15,
      minPurchase: 100,
      maxUses: 200,
      usedCount: 45,
      validFrom: new Date('2026-01-01'),
      validUntil: new Date('2026-12-31'),
      isActive: true,
    },
    {
      id: 'promo-4',
      code: 'SPRING25',
      description: '$25 off spring workshop registration',
      discountType: 'FIXED',
      discountValue: 25,
      minPurchase: 65,
      maxUses: 100,
      usedCount: 8,
      validFrom: new Date('2026-03-01'),
      validUntil: new Date('2026-05-31'),
      isActive: true,
    },
    {
      id: 'promo-5',
      code: 'HOLIDAY15',
      description: '15% off holiday gift guide items',
      discountType: 'PERCENTAGE',
      discountValue: 15,
      minPurchase: 75,
      maxUses: 300,
      usedCount: 0,
      validFrom: new Date('2026-11-15'),
      validUntil: new Date('2026-12-25'),
      isActive: false,
    },
  ];

  for (const promo of promoCodesData) {
    await prisma.promoCode.create({ data: promo });
  }
  console.log(`  Created ${promoCodesData.length} promo codes.`);

  // ─── Scheduled Content ─────────────────────────────────────
  console.log('Seeding scheduled content...');
  const scheduledContentData = [
    {
      id: 'sc-1',
      title: 'Studio Process: Golden Hour Painting',
      type: 'journal_post',
      scheduledAt: new Date('2026-03-12T09:00:00Z'),
      status: 'scheduled',
      channel: 'blog',
      contentRef: 'j-draft-4',
    },
    {
      id: 'sc-2',
      title: 'Spring Workshop Reminder — Last Spots',
      type: 'email_blast',
      scheduledAt: new Date('2026-03-15T10:00:00Z'),
      status: 'scheduled',
      channel: 'email',
      contentRef: 'camp-2',
    },
    {
      id: 'sc-3',
      title: 'New Work Preview — Carousel Post',
      type: 'social_post',
      scheduledAt: new Date('2026-03-14T17:00:00Z'),
      status: 'scheduled',
      channel: 'instagram',
    },
    {
      id: 'sc-4',
      title: 'VIP Private Viewing Invitation',
      type: 'campaign_post',
      scheduledAt: new Date('2026-03-20T08:00:00Z'),
      status: 'scheduled',
      channel: 'email',
      contentRef: 'camp-3',
    },
    {
      id: 'sc-5',
      title: 'Behind the Scenes Reel',
      type: 'social_post',
      scheduledAt: new Date('2026-03-18T16:00:00Z'),
      status: 'scheduled',
      channel: 'instagram',
    },
    {
      id: 'sc-6',
      title: "Collector's Guide Part 2",
      type: 'journal_post',
      scheduledAt: new Date('2026-03-25T09:00:00Z'),
      status: 'scheduled',
      channel: 'blog',
      contentRef: 'j-draft-5',
    },
    {
      id: 'sc-7',
      title: 'Print Sale Announcement',
      type: 'email_blast',
      scheduledAt: new Date('2026-03-28T10:00:00Z'),
      status: 'scheduled',
      channel: 'email',
    },
    {
      id: 'sc-8',
      title: 'Workshop Recap & Testimonials',
      type: 'social_post',
      scheduledAt: new Date('2026-03-10T14:00:00Z'),
      status: 'published',
      channel: 'facebook',
    },
  ];

  for (const sc of scheduledContentData) {
    await prisma.scheduledContent.create({ data: sc });
  }
  console.log(`  Created ${scheduledContentData.length} scheduled content items.`);

  // ─── Settings ──────────────────────────────────────────────
  console.log('Seeding settings...');
  const settingsData = [
    {
      id: 'setting-1',
      key: 'gallery_name',
      value: 'Mona Niko Gallery',
    },
    {
      id: 'setting-2',
      key: 'gallery_email',
      value: 'info@monaniko.com',
    },
    {
      id: 'setting-3',
      key: 'gallery_phone',
      value: '(949) 555-0127',
    },
    {
      id: 'setting-4',
      key: 'gallery_address',
      value: JSON.stringify({
        line1: '668B The Shops At Mission Viejo Mall',
        city: 'Mission Viejo',
        state: 'CA',
        zip: '92691',
        country: 'US',
      }),
    },
    {
      id: 'setting-5',
      key: 'gallery_hours',
      value: JSON.stringify({
        monday: '10:00 AM - 9:00 PM',
        tuesday: '10:00 AM - 9:00 PM',
        wednesday: '10:00 AM - 9:00 PM',
        thursday: '10:00 AM - 9:00 PM',
        friday: '10:00 AM - 9:00 PM',
        saturday: '10:00 AM - 9:00 PM',
        sunday: '11:00 AM - 7:00 PM',
      }),
    },
    {
      id: 'setting-6',
      key: 'tax_rate',
      value: '0.085',
    },
    {
      id: 'setting-7',
      key: 'shipping_flat_rate',
      value: '12',
    },
    {
      id: 'setting-8',
      key: 'free_shipping_threshold',
      value: '500',
    },
  ];

  for (const s of settingsData) {
    await prisma.setting.create({ data: s });
  }
  console.log(`  Created ${settingsData.length} settings.`);

  console.log('');
  console.log('Seed completed successfully!');
  console.log('Summary:');
  console.log(`  Users: 1`);
  console.log(`  Collections: ${collectionsData.length}`);
  console.log(`  Artworks: ${artworksData.length}`);
  console.log(`  Products: ${productsData.length}`);
  console.log(`  Workshops: ${workshopsData.length}`);
  console.log(`  Journal Posts: ${journalPostsData.length}`);
  console.log(`  Testimonials: ${testimonialsData.length}`);
  console.log(`  Press Items: ${pressItemsData.length}`);
  console.log(`  Inquiries: ${inquiriesData.length}`);
  console.log(`  Subscribers: ${subscribersData.length}`);
  console.log(`  Orders: ${ordersData.length}`);
  console.log(`  Campaigns: ${campaignsData.length}`);
  console.log(`  Promo Codes: ${promoCodesData.length}`);
  console.log(`  Scheduled Content: ${scheduledContentData.length}`);
  console.log(`  Settings: ${settingsData.length}`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error('Seed failed:', e);
    await prisma.$disconnect();
    process.exit(1);
  });
